name: Packer Build

env:
    PORT:  ${{ secrets.PORT}}
    TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
    TEST_DB_USERNAME : ${{ secrets.TEST_DB_USERNAME }}
    TEST_DB_PASSWORD : ${{ secrets.TEST_DB_PASSWORD }}
    host : ${{ secrets.HOST }}
    dialect: ${{ secrets.DIALECT }}


# This workflow is triggered on a pull request
on:
  pull_request:
    types: [closed]

#Below are jobs for testing 
jobs:
  test2:
    if: github.event.pull_request.merged == true
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'
        

      # Setup 3: Set up postgres and create database test
      - name: Set up Postgres
        run: |
            sudo apt update
            sudo apt-get install -y postgresql postgresql-contrib
            sudo systemctl start postgresql
            sudo systemctl enable postgresql
            POSTGRES_PASSWORD=${{ secrets.TEST_DB_PASSWORD }}
            sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '$POSTGRES_PASSWORD';"
            sudo -u postgres createdb ${{ secrets.TEST_DB_NAME }}
    
      - name: Configure Environment Variables
        run: |
            echo > .env
            echo PORT=${{ secrets.PORT }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
            echo TEST_DB_NAME=${{ secrets.TEST_DB_NAME }} >> .env
            echo TEST_DB_USERNAME=${{ secrets.TEST_DB_USERNAME }} >> .env
            echo TEST_DB_PASSWORD=${{ secrets.TEST_DB_PASSWORD }} >> .env
            echo host=${{ secrets.HOST }} >> .env
            echo dialect=${{ secrets.DIALECT }} >> .env
            
      - name: Zip webapp 
        run: |
          zip -r webapp.zip ./
          ls 
          cat .env

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run your tests, securely passing the database URL using secrets
      - name: Run tests
        run: npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: "${{ vars.AWS_REGION }}"

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
            version: "latest"

      - name: Configure Packer Environment Variables
        run: |
          echo > aws.pkrvars.hcl
          echo aws_region=\"${{ vars.AWS_REGION }}\" >> aws.pkrvars.hcl
          echo device_name=\"${{vars.DEVICE_NAME }}\" >> aws.pkrvars.hcl
          echo instance_type=\"${{ vars.INSTANCE_TYPE }}\" >> aws.pkrvars.hcl
          echo ssh_username=\"${{ vars.SSH_USERNAME }}\" >> aws.pkrvars.hcl
          echo source_ami=\"${{ vars.SOURCE_AMI }}\" >> aws.pkrvars.hcl
          echo subnet_id=\"${{ vars.SUBNET_ID }}\" >> aws.pkrvars.hcl
          echo volume_size=\"${{ vars.VOLUME_SIZE }}\" >> aws.pkrvars.hcl
            
      - name: Initialize Packer
        run: "packer init ./aws.pkr.hcl"

      - name: Packer Validate
        run: "packer validate --var-file=aws.pkrvars.hcl ./aws.pkr.hcl"

      - name: Packer build
        run: "packer build --var-file=aws.pkrvars.hcl ./aws.pkr.hcl"