name: Packer Template Lint and Validate

on:
  pull_request:
    branches:
      - main  

jobs:
  packer-lint-validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install HashiCorp Packer
      - name: Set up HashiCorp Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest  

      - name: Zip webapp 
        run: |
             zip -r webapp.zip ./
             ls 
      
      - name: Configure Packer Environment Variables
        run: |
          set -x  
          touch aws.pkvars.hcl
          echo aws_region=\"${{ secrets.AWS_REGION }}\" >> aws.pkvars.hcl
          echo instance_type=\"${{ vars.INSTANCE_TYPE }}\" >> aws.pkvars.hcl
          echo ssh_username=\"${{ vars.SSH_USERNAME }}\" >> aws.pkvars.hcl
          echo source_ami=\"${{ vars.SOURCE_AMI }}\" >> aws.pkvars.hcl
          echo subnet_id=\"${{ vars.SUBNET_ID }}\" >> aws.pkvars.hcl

      - name: Verify aws.pkvars.hcl Creation
        run: cat aws.pkvars.hcl
        

      - name: Run packer init
        run: "packer init aws.pkr.hcl"

      # Run packer fmt -check
      - name: Run Packer FMT Check
        run: |
          packer fmt -check aws.pkr.hcl
        continue-on-error: false  

      # Run packer validate
      - name: Run Packer Validate
        run: "packer validate --var-file=aws.pkvars.hcl ./aws.pkr.hcl"
        continue-on-error: false  
