name: Packer Template Lint and Validate

on:
  pull_request:
    branches:
      - main  

jobs:
  packer-lint-validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install HashiCorp Packer
      - name: Set up HashiCorp Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      # Initialize Packer
      - name: Initialize Packer
        run: packer init aws.pkr.hcl

      # Format Packer Config
      - name: Format Packer Config
        run: packer fmt aws.pkr.hcl
        id: fmt

      # Check for Formatting Changes
      - name: Check for Formatting Changes
        run: |
          CHANGES=$(git diff --name-only)
          if [[ -n "$CHANGES" ]]; then
            echo "Packer format check failed. The following files have formatting changes:"
            echo "$CHANGES"
            exit 1

      # Validate Packer Config
      - name: Validate Packer Config
        run: packer validate aws.pkr.hcl
